create table public.notes (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

alter table public.notes enable row level security;

grant select, insert, update, delete on public.notes to authenticated;
grant usage, select on sequence public.notes_id_seq to authenticated;

create policy "Users can read their own notes"
on public.notes
for select
to authenticated
using (auth.uid() = owner_id);

create policy "Users can insert their own notes"
on public.notes
for insert
to authenticated
with check (auth.uid() = owner_id);

create policy "Users can update their own notes"
on public.notes
for update
to authenticated
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

create policy "Users can delete their own notes"
on public.notes
for delete
to authenticated
using (auth.uid() = owner_id);
