import type { DatabaseSession } from "./contract.ts";

export const SYSTEM_SCHEMA_SQL = `
  create schema if not exists auth;
  create schema if not exists storage;
  create schema if not exists supabase_migrations;
  create schema if not exists minibase_meta;

  do $block$
  begin
    if not exists (select 1 from pg_roles where rolname = 'anon') then
      create role anon nologin;
    end if;
    if not exists (select 1 from pg_roles where rolname = 'authenticated') then
      create role authenticated nologin;
    end if;
    if not exists (select 1 from pg_roles where rolname = 'service_role') then
      create role service_role nologin bypassrls;
    end if;
  end
  $block$;

  create or replace function auth.jwt()
  returns jsonb
  language sql
  stable
  as $function$
    select coalesce(
      nullif(current_setting('request.jwt.claims', true), '')::jsonb,
      '{}'::jsonb
    )
  $function$;

  create or replace function auth.uid()
  returns uuid
  language sql
  stable
  as $function$
    select nullif(
      coalesce(
        nullif(current_setting('request.jwt.claim.sub', true), ''),
        auth.jwt() ->> 'sub'
      ),
      ''
    )::uuid
  $function$;

  create or replace function auth.role()
  returns text
  language sql
  stable
  as $function$
    select coalesce(
      nullif(current_setting('request.jwt.claim.role', true), ''),
      auth.jwt() ->> 'role'
    )
  $function$;

  create table if not exists auth.users (
    instance_id uuid,
    id uuid primary key,
    aud varchar(255),
    role varchar(255),
    email varchar(255),
    encrypted_password varchar(255),
    email_confirmed_at timestamptz,
    invited_at timestamptz,
    confirmation_token varchar(255),
    confirmation_sent_at timestamptz,
    recovery_token varchar(255),
    recovery_sent_at timestamptz,
    email_change_token_new varchar(255),
    email_change varchar(255),
    email_change_sent_at timestamptz,
    last_sign_in_at timestamptz,
    raw_app_meta_data jsonb default '{}'::jsonb,
    raw_user_meta_data jsonb default '{}'::jsonb,
    is_super_admin boolean,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    phone text,
    phone_confirmed_at timestamptz,
    confirmed_at timestamptz,
    is_anonymous boolean not null default false,
    banned_until timestamptz
  );

  create unique index if not exists users_email_unique
  on auth.users(lower(email))
  where email is not null;

  create table if not exists auth.sessions (
    id uuid primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    revoked_at timestamptz
  );

  alter table auth.sessions add column if not exists revoked_at timestamptz;

  create table if not exists auth.refresh_tokens (
    id bigint generated by default as identity primary key,
    token_hash text not null unique,
    user_id uuid not null references auth.users(id) on delete cascade,
    session_id uuid not null references auth.sessions(id) on delete cascade,
    created_at timestamptz not null default now(),
    expires_at timestamptz not null,
    revoked_at timestamptz
  );

  create table if not exists auth.audit_log (
    id bigint generated by default as identity primary key,
    actor_role text not null,
    actor_id uuid,
    action text not null,
    target_user_id uuid,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
  );

  create table if not exists storage.buckets (
    id text primary key,
    name text not null unique,
    owner uuid,
    public boolean default false,
    file_size_limit bigint,
    allowed_mime_types text[],
    created_at timestamptz default now(),
    updated_at timestamptz default now()
  );

  create table if not exists storage.objects (
    id uuid primary key,
    bucket_id text not null references storage.buckets(id) on delete cascade,
    name text not null,
    owner uuid,
    metadata jsonb default '{}'::jsonb,
    path_tokens text[] generated always as (string_to_array(name, '/')) stored,
    version text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    last_accessed_at timestamptz default now(),
    unique(bucket_id, name)
  );

  alter table storage.objects
    add column if not exists user_metadata jsonb default '{}'::jsonb;

  alter table storage.objects enable row level security;

  create table if not exists supabase_migrations.schema_migrations (
    version text primary key,
    name text not null,
    statements text[],
    hash text not null,
    applied_at timestamptz not null default now()
  );

  create table if not exists minibase_meta.seed_history (
    hash text primary key,
    applied_at timestamptz not null default now()
  );

  create table if not exists minibase_meta.migration_attempts (
    version text primary key,
    name text not null,
    hash text not null,
    transactional boolean not null,
    state text not null check (state in ('running', 'failed', 'applied')),
    attempt integer not null check (attempt > 0),
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    error_code text
  );

  grant usage on schema public, auth, storage to anon, authenticated, service_role;
  grant execute on function auth.jwt(), auth.uid(), auth.role()
    to anon, authenticated, service_role;
  grant all on auth.users, auth.sessions, auth.refresh_tokens, auth.audit_log to service_role;
  grant all on storage.buckets, storage.objects to service_role;
  grant select, insert, update, delete on storage.objects to authenticated;
  grant all privileges on all tables in schema public to service_role;
  grant all privileges on all sequences in schema public to service_role;
  alter default privileges in schema public
    grant all privileges on tables to service_role;
  alter default privileges in schema public
    grant all privileges on sequences to service_role;
`;

export async function bootstrapSystemSchema(session: DatabaseSession): Promise<void> {
  await session.exec(SYSTEM_SCHEMA_SQL);
}
